# Generated by Django 4.0.4 on 2022-08-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_photocontest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photocontest',
            name='Photo',
        ),
        migrations.AddField(
            model_name='photocontest',
            name='photo',
            field=models.ImageField(blank=True, help_text='Please upload an Image.', null=True, upload_to=''),
        ),
    ]
