# Generated by Django 4.0.4 on 2022-08-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_photocontest_photo_photocontest_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocontest',
            name='photo',
            field=models.ImageField(blank=True, help_text='Please upload an Image.', upload_to=''),
        ),
    ]
